trigger:
  batch: true
  branches:
    include:
      - "*"

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "##vso[build.updatebuildnumber]$(git rev-parse --short HEAD)"
  displayName: Set Build Number
  
- task: UseRubyVersion@0
  displayName: Use Ruby Version > 2.7
  inputs:
    versionSpec: '>= 2.7'

- script: |
    ruby --version
    gem install bundler:2.1.4
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: bundle exec rubocop
  displayName: 'Run RuboCop'

- script: bundle exec rspec
  displayName: 'Run RSpec'
  env:
    DEPLOYERS: 'AzureDevOps'

- task: Docker@2
  displayName: Build Docker
  inputs:
    containerRegistry: 'DfE Docker Hub'
    repository: 'dfedigital/apply-ops-dashboard'
    command: 'buildAndPush'
    tags: |
      $(Build.BuildNumber)
