---
name: 'Apply Ops Dashboard CI'

on:
  pull_request: {}

jobs:
  rspec:
    name: 'RSpec'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: 'Set up Ruby from .ruby-version'
        uses: ruby/setup-ruby@v1

      - name: 'Install dependencies'
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: 'Run tests'
        run: |
          bundle exec rspec

  linting:
    name: 'Linting'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: 'Set up Ruby from .ruby-version'
        uses: ruby/setup-ruby@v1

      - name: 'Build App'
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: 'Run linters'
        run: |
          bundle exec rubocop
